services:
  <service_name>:
    image: 
    container_name: 
    network_mode: host
    env_file:
      - stack.env
    volumes:
      - ${DOCKERDIR}/<service_name>/config:/config
    restart: unless-stopped