services:
  Plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: Plex
    network_mode: host
    environment:
      - VERSION=latest
    env_file:
      - stack.env
    devices:
      - /dev/dri:/dev/dri
    volumes:
      - ${DOCKERDIR}/Plex/config:/config
      - ${DOCKERDIR}/Plex/transcode:/transcode
      #- /dev/shm:/transcode
      - ${MEDIADIR}:/media
    restart: unless-stopped
    
  kitana:
    image: pannal/kitana:latest
    container_name: kitana
    volumes:
      - ${DOCKERDIR}/Kitana/data:/app/data
    env_file:
      - stack.env
    ports:
      - 31337:31337
    #links:
    #  - plex
    restart: unless-stopped

  Tautulli:
    image: linuxserver/tautulli:latest
    container_name: Tautulli
    volumes:
      - ${DOCKERDIR}/Tautulli/config:/config
    env_file:
      - stack.env
    ports:
      - 8181:8181
    network_mode: host
    restart: unless-stopped