services:
  Plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: Plex
    network_mode: host
    environment:
      - VERSION=latest
    env_file:
      - stack.env
    devices:
      - /dev/dri:/dev/dri
    volumes:
      - ${DOCKERDIR}/Plex/config:/config
      - ${DOCKERDIR}/Plex/transcode:/transcode
      #- /dev/shm:/transcode
      - ${MEDIADIR}:/media
    restart: unless-stopped
    
  kitana:
    image: pannal/kitana:latest
    container_name: kitana
    volumes:
      - ${DOCKERDIR}/Kitana/data:/app/data
    env_file:
      - stack.env
    ports:
      - 31337:31337
    #links:
    #  - plex
    restart: unless-stopped

  Tautulli:
    image: linuxserver/tautulli:latest
    container_name: Tautulli
    volumes:
      - ${DOCKERDIR}/Tautulli/config:/config
    env_file:
      - stack.env
    ports:
      - 8181:8181
    network_mode: host
    restart: unless-stopped
      
  threadfin:
    image: fyb3roptik/threadfin:latest
    container_name: Threadfin
    hostname: threadfin
    restart: unless-stopped
    network_mode: host
    ports:
      - 34401:34401
    environment:
      - THREADFIN_UID=${PUID}
      - THREADFIN_GID=${PGID}
      - THREADFIN_PORT=34401
      - THREADFIN_DEBUG=0
      - THREADFIN_BRANCH=main
    env_file:
      - stack.env
    devices:
      - /dev/dri:/dev/dri
    volumes:
      - ${DOCKERDIR}/threadfin/conf/:/home/threadfin/conf:rw