services:
  server:
    image: gitea/gitea:latest
    container_name: gitea
    env_file:
      - stack.env
    restart: always
    networks:
      - gitea
    volumes:
      - ${DOCKERDIR}/gitea/data:/data
      - ${GIT_DIR}:/git
    ports:
      - ${HTTP_PORT}:3000
      - ${SSH_PORT}:22

networks:
  gitea:
    external: false
